backend:
  name: git-gateway
  branch: main  # or master (check your repo branch)

media_folder: "uploads"     # where files will be stored in repo
public_folder: "/uploads"   # how users will access them

collections:
  - name: "files"
    label: "Files"
    folder: "content/files"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "File", name: "file", widget: "file"}
